### ISSUE TITLE
Segmentation faul HandleReceivedExplicitTcpData

### ISSUE THREAD

**Issue by frandiaznet** [liftoff-sr/CIPster#10]
Hi all, I have a problem with the connection. Some month ago, I wrote a program to conenct via Ethernet/Ip with a machine that use the same protocol. I configured the assembly and it worked.
Now I have to connect with another machine where the manufacture need a EDS file. I creted an EDS file and send it but when we go to try to connect, I get this error: 

![screenshot from 2018-09-04 09 56 54](https://user-images.githubusercontent.com/1622706/45019662-32607800-b02d-11e8-9bcb-fe01aaee2bab.png)

Error with more info and DEGUB flag activate
![screenshot from 2018-09-04 09 58 46](https://user-images.githubusercontent.com/1622706/45019661-32607800-b02d-11e8-8e1f-39d31b4a2b6c.png)

I think that is related with the data but at this moment I dont know. Im searching since 2 week read and read, see the library and the code, but I can not find the error.

I post this message in case any person get the same error or if there is any method to identify or get more info.

Thank you in advance.

Regards,
Fran.

**Comment by liftoff-sr** [comment]
You have no source code debugger?

If not, then what I would do is duplicate the assembly numbers in modifications to the
POSIX sample application. Then I would run that modified sample program on a desktop
computer under a source debugger.  You will have to assume the IP address of the original
target, or temporarily tell your originator to talk to the desktop compute instead of the
original node.

You should be able to duplicate the same problem first before even bringing in the
debugger.  That is, if the problem is actually in the stack.  After that first run or a
few runs to polish the sample program with a goal of duplicating the crash, then bring in
the source debugger on a Debug build.

Any source fix in that temporary environment (node substituion) will likely then fix the
actual target's behaviour.

I also would be using the latest stack source code at this point, given that the code you
are using is not working.

There is a possibility that the crash is not in the stack, but the above strategy will
probably tell you that also.

It looks like you have a stray or bashed function pointer, the execution stream seems to
have ended up in __start which is not normal so long after startup.  Put a break point in
the correct spot and single step after that.
