### ISSUE TITLE
Two adapters in One host (the host has two NIC)

### ISSUE THREAD

**Issue by xixi647** [liftoff-sr/CIPster#5]
I open two adapters in one host PC, and the PC has two NICs, and When PLC connect with these two adapters with forward open service  Cyclic class 1.  The problem happens.

we have two IP address 192.168.2.2 and 192.168.2.3 for two adapter. 
adapter 1 (192.168.2.2) successfully establish IO connections to PLC, 
but adapter 2 (192.168.2.3) not. 

adapter 2 send udp data with another IP 192.168.2.2.

I think the two adaptes mix the two IPs. 
Once the IO connections established, The adapter 2 create a new producing socket. In this case, we use this new create socket to send UDP data, we cannot determine the send IP address, this will be a issue.

**Comment by liftoff-sr** [comment]
On 10/27/2017 05:14 AM, xixi647 wrote:
> I open two adapters in one host PC, and the PC has two NICs, and When PLC connect with
> these two adapters with forward open service Cyclic class 1. The problem happens.

1) How is this possible to configure two adapters in the host PC?  I see the public API
function ConfigureNetworkInterface(), and I see that it using a global structure called
"interface_configuration_" in ciptcpipinterface.c.  I don't think the stack currently
supports more than one interface as a result of this global (single instance).  Obviously
an enhancement is possible, and it seems necessary for your situation as I understand it.

2) Since both your IP addresses are on the same subnet, I wonder if your TCP/IP routing
table needs augmentation (internal to the OS, not in the CIPster stack) .  The default
setup would probably allow the TCP/IP stack to send out either interface, the one with the
first matching subnet/mask combination matching the destination.  You would have to
manually modify the routing table with two entries in order to cherry pick how you want
reply traffic to be sent.  Or pick IP addresses which are not on the same subnet.


> 
> we have two IP address 192.168.2.2 and 192.168.2.3 for two adapter.
> adapter 1 (192.168.2.2) successfully establish IO connections to PLC,
> but adapter 2 (192.168.2.3) not.
> 
> adapter 2 send udp data with another IP 192.168.2.2.
> 
> I think the two adaptes mix the two IPs.
> Once the IO connections established, The adapter 2 create a new producing socket. In this
> case, we use this new create socket to send UDP data, we cannot determine the send IP
> address, this will be a issue.

**Comment by liftoff-sr** [comment]
https://stackoverflow.com/questions/563235/linux-how-do-i-force-a-specific-network-interface-to-be-used


Among the solutions listed is to virtualize the process.  Although somewhat ambiguous, one
interpretation is to use a VM.

With the costs of computers's so low, why not another computer altogether?
