### ISSUE TITLE
.EDS File

### ISSUE THREAD

**Issue by curtiskoelling** [liftoff-sr/CIPster#8]
Is /data/opener_sample_app.eds still representative of the sample application?
(/examples/POSIX/sample_application/sampleapplication.cc)
I am new to Ethernet/IP and I have a client that would like an EDS file that he can use when he sets up his PLC to interact with my device. I am trying to learn by example but I feel like the two might have diverged at some point.

**Comment by liftoff-sr** [comment]
Since nobody has made an effort to keep these in sync, and because the sample applications
are quite arbitrary, they are certainly diverged.

If you are an ODVA member, and maybe even if you are not, I thought ODVA provided a tool
called "Easy EDS"  or something similar.

Another option is to find another vendor's *simplest* EDS files and doctor the assembly
IDs to match what you do in the sample application.  I don't think this is hard with a
simple text editor, especially if you have the Ethernet/IP spec in hand opened to the EDS
section.
